name: Validate Conventional Commits

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches:
      - master
      - develop

jobs:
  lint-commits:
    name: Validate PR Title & Commits
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Commitlint
        run: npm install --no-save @commitlint/config-conventional @commitlint/cli

      - name: Validate PR Title
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          echo "$PR_TITLE" | npx commitlint --config .github/commitlint.config.js

      - name: Validate Commits in PR
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --config .github/commitlint.config.js
